# Generated by Django 6.0.8 on 2026-09-05 15:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def check_existing_ratings(apps, schema_editor):
    Review = apps.get_model('movies', 'Review')
    invalid = Review.objects.using(schema_editor.connection.alias).exclude(rating__range=(1, 5))
    if invalid.exists():
        raise RuntimeError('Existing reviews have ratings outside 1-5. Back up the database and correct these ratings before migrating; no reviews were deleted.')


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_existing_ratings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'),
        ),
    ]
